// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: grpc_proto/grpc.proto

//declaring the service

package grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_proto_grpc_proto_rawDescGZIP(), []int{0}
}

type EmpInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mid  string      `protobuf:"bytes,3,opt,name=mid,proto3" json:"mid,omitempty"`
	Dept *Department `protobuf:"bytes,4,opt,name=dept,proto3" json:"dept,omitempty"`
}

func (x *EmpInfo) Reset() {
	*x = EmpInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmpInfo) ProtoMessage() {}

func (x *EmpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmpInfo.ProtoReflect.Descriptor instead.
func (*EmpInfo) Descriptor() ([]byte, []int) {
	return file_grpc_proto_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *EmpInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmpInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmpInfo) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *EmpInfo) GetDept() *Department {
	if x != nil {
		return x.Dept
	}
	return nil
}

type Department struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Department) Reset() {
	*x = Department{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_grpc_proto_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_grpc_proto_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_grpc_proto_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_grpc_proto_grpc_proto protoreflect.FileDescriptor

var file_grpc_proto_grpc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x68, 0x0a, 0x07, 0x45, 0x6d, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x64, 0x65,
	0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67,
	0x6d, 0x74, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64,
	0x65, 0x70, 0x74, 0x22, 0x30, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x1e, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x32, 0x8b, 0x02, 0x0a, 0x07, 0x45, 0x6d, 0x70, 0x43, 0x52, 0x55, 0x44, 0x12, 0x34, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x0e, 0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x10, 0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x30, 0x01, 0x12, 0x2e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x0b, 0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x49,
	0x64, 0x1a, 0x10, 0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x10, 0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d,
	0x74, 0x2e, 0x45, 0x6d, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0b, 0x2e, 0x65, 0x6d, 0x70, 0x6d,
	0x67, 0x6d, 0x74, 0x2e, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6d, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x10, 0x2e, 0x65, 0x6d, 0x70,
	0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x45, 0x6d, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0f, 0x2e, 0x65,
	0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a,
	0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x0b, 0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x49, 0x64, 0x1a, 0x0f,
	0x2e, 0x65, 0x6d, 0x70, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42,
	0x16, 0x5a, 0x14, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_grpc_proto_rawDescOnce sync.Once
	file_grpc_proto_grpc_proto_rawDescData = file_grpc_proto_grpc_proto_rawDesc
)

func file_grpc_proto_grpc_proto_rawDescGZIP() []byte {
	file_grpc_proto_grpc_proto_rawDescOnce.Do(func() {
		file_grpc_proto_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_grpc_proto_rawDescData)
	})
	return file_grpc_proto_grpc_proto_rawDescData
}

var file_grpc_proto_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_proto_grpc_proto_goTypes = []interface{}{
	(*Empty)(nil),      // 0: empmgmt.Empty
	(*EmpInfo)(nil),    // 1: empmgmt.EmpInfo
	(*Department)(nil), // 2: empmgmt.Department
	(*Id)(nil),         // 3: empmgmt.Id
	(*Status)(nil),     // 4: empmgmt.Status
}
var file_grpc_proto_grpc_proto_depIdxs = []int32{
	2, // 0: empmgmt.EmpInfo.dept:type_name -> empmgmt.Department
	0, // 1: empmgmt.EmpCRUD.GetEmpsDetails:input_type -> empmgmt.Empty
	3, // 2: empmgmt.EmpCRUD.GetEmpDetails:input_type -> empmgmt.Id
	1, // 3: empmgmt.EmpCRUD.CreateEmpDetails:input_type -> empmgmt.EmpInfo
	1, // 4: empmgmt.EmpCRUD.UpdateEmpDetails:input_type -> empmgmt.EmpInfo
	3, // 5: empmgmt.EmpCRUD.DeleteEmpDetails:input_type -> empmgmt.Id
	1, // 6: empmgmt.EmpCRUD.GetEmpsDetails:output_type -> empmgmt.EmpInfo
	1, // 7: empmgmt.EmpCRUD.GetEmpDetails:output_type -> empmgmt.EmpInfo
	3, // 8: empmgmt.EmpCRUD.CreateEmpDetails:output_type -> empmgmt.Id
	4, // 9: empmgmt.EmpCRUD.UpdateEmpDetails:output_type -> empmgmt.Status
	4, // 10: empmgmt.EmpCRUD.DeleteEmpDetails:output_type -> empmgmt.Status
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_grpc_proto_init() }
func file_grpc_proto_grpc_proto_init() {
	if File_grpc_proto_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmpInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Department); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_grpc_proto_goTypes,
		DependencyIndexes: file_grpc_proto_grpc_proto_depIdxs,
		MessageInfos:      file_grpc_proto_grpc_proto_msgTypes,
	}.Build()
	File_grpc_proto_grpc_proto = out.File
	file_grpc_proto_grpc_proto_rawDesc = nil
	file_grpc_proto_grpc_proto_goTypes = nil
	file_grpc_proto_grpc_proto_depIdxs = nil
}
